### ISSUE TITLE
raw data needed

### ISSUE THREAD

**Issue by ZhengguoTan** [AmirHeydariGit/joint_maple#1]
Dear Dr. Heydari,

Thank you for providing the excellent open-source code. 

In the `Main.ipynb`, it requires the raw k-space data 'raw_slice_25.mat', which is not in the `dataset/` folder yet.

May you kindly provide this data when possible?

Best Regards,
Zhengguo

**Comment by AmirHeydariGit** [comment]
​Hi Zhengguo,
Thank you for reaching out. Here you can find the Drop box link for the raw data:
https://www.dropbox.com/scl/fi/391sly8h5bw3vfuqdbsv6/raw_slice_25.mat?rlkey=hl4o1ataic4vezikdh6m4dgsx&dl=0

I will try to put the raw data on Github ASAP. 
Please let me know if there is any problem with the data or code.
The best,
Amir
   
On Tue, 03 Bahman 1402 01:37 PM, Zhengguo Tan ***@***.***> wrote:
> Dear Dr. Heydari,
Thank you for providing the excellent open-source code.
In the Main.ipynb, it requires the raw k-space data 'raw_slice_25.mat', which is not in the dataset/ folder yet.
May you kindly provide this data when possible?
Best Regards,
> 
Zhengguo
